#-*- coding: utf-8 -*-

class varname_hangulvarname_explain:

    def get_varname_hangulvarname(self):
        var_hanvar = {'age': '나이',
                      'approve_mean_timeh': '평균_결재소요시간',
                      'approve_tot_request': '총_결재요청횟수',
                      'apprvoe_tot_sign': '총_결재결재횟수',
                      'blog_tot_checked': '총_게시글_피조회횟수',
                      'blog_tot_visit': '총_타블로그_접속횟수',
                      'blog_tot_visited': '총_my블로그_방문자수',
                      'btrip_nbr': '출장 일수 ',
                      'bu': '부',
                      'buha_betweenness': '부하_매개중심성',
                      'buha_closeness': '부하_근접중심성',
                      'buha_eigenvector': '부하_고유벡터중심성',
                      'buha_indegree': '부하_연결내향중심성',
                      'buha_outdegree': '부하_연결외향중심성',
                      'cafe_meanm_pg1f': '평균월_카페판교1층_이용금액',
                      'cafe_meanm_pg3f': '평균월_카페판교3층_이용금액',
                      'cafe_tot_spend': '총_카페_이용금액',
                      'cafe_totm_pg1f': '총_카페판교1층_이용월횟수',
                      'cafe_totm_pg3f': '총_카페판교3층_이용월횟수',
                      'cct1': '업무몰입도 13번 질문 점수',
                      'cct2': '업무몰입도 14번 질문 점수',
                      'cct3': '업무몰입도 15번 질문 점수',
                      'cct4': '업무몰입도 16번 질문 점수',
                      'cct5': '업무몰입도 17번 질문 점수',
                      'cct_avg': '업무몰입도 평균 점수',
                      'cct_no_reply_nbr': '무응답 개수',
                      'coreyn': '핵심인재유무',
                      'decode_tot': '복호화 횟수 ',
                      'diff_dep_high_betweenness': '다른부서 높은레벨_매개중심성',
                      'diff_dep_high_closeness': '다른부서 높은레벨_근접중심성',
                      'diff_dep_high_eigenvector': '다른부서 높은레벨_고유벡터중심성',
                      'diff_dep_high_indegree': '다른부서 높은레벨_연결내향중심성',
                      'diff_dep_high_outdegree': '다른부서 높은레벨_연결외향중심성',
                      'diff_dep_low_betweenness': '다른부서 낮은레벨_매개중심성',
                      'diff_dep_low_closeness': '다른부서 낮은레벨_근접중심성',
                      'diff_dep_low_eigenvector': '다른부서 낮은레벨_고유벡터중심성',
                      'diff_dep_low_indegree': '다른부서 낮은레벨_연결내향중심성',
                      'diff_dep_low_outdegree': '다른부서 낮은레벨_연결외향중심성',
                      'docu_decoding_mean_timeh': '평균_문서복호화_결재소요시간',
                      'docu_decoding_tot_n': '총_문서복호화_신청문서건수',
                      'docu_decoding_tot_requet': '총_문서복호화_요청횟수',
                      'docu_decoding_tot_sign': '총_문서복호화_결재횟수',
                      'dongryo_betweenness': '동료_매개중심성',
                      'dongryo_closeness': '동료_근접중심성',
                      'dongryo_eigenvector': '동료_고유벡터중심성',
                      'dongryo_indegree': '동료_연결내향중심성',
                      'dongryo_outdegree': '동료_연결외향중심성',
                      'eat_tot_spend': '총_식당카페_이용금액',
                      'ecm_after_lunch1314': '13시~14시까지 점심후 ECM 이용 일',
                      'ecm_after_out1904': '19시~4시까지 야근 ECM 이용 일',
                      'ecm_before_in79': '7시~9시까지 출근전 ECM 이용 일',
                      'ecm_before_out1718': '17시~18시까지 퇴근전 ECM 이용 일',
                      'ecm_tot_enroll': '총_ECM_등록횟수',
                      'edu_abroad': '해외연수이수학점',
                      'edu_course_cnt': '교육이수학점',
                      'edu_job': '직무이수학점',
                      'edu_license': '자격취득이수학점',
                      'edu_nbr': '교육이수과정수',
                      'edu_njob': '비직무이수학점 ',
                      'edu_out_ratio': '학점사외이수비율',
                      'email_after_lunch1314_mean': '13시~14시까지 점심후 메일 발신 횟수 평균',
                      'email_between_1904_daycnt_send': '19시~4시까지 야근 메일 발신 일 수 ',
                      'email_between_1904_mean_send': '19시~4시까지 야근메일 발신 횟수 평균',
                      'email_before_out1718_mean': '17시~18시까지 퇴근전 메일 발신 횟수 평균',
                      'email_between_0709_daycnt_send': '7시~9시까지 출근전 메일 발신 일 수',
                      'email_before_time79_mean': '7시~9시까지 출근전 메일 발신 횟수 평균',
                      'email_day_mean_receive': '이메일 하루 평균 수신 수 ',
                      'email_day_mean_send': '이메일 하루 평균 발신 수 ',
                      'email_day_var_receive': '이메일 하루 분산 수신 수 ',
                      'email_day_var_send': '이메일 하루 분산 발신 수',
                      'email_month_mean_receive': '이메일 월 평균 수신 수 ',
                      'email_month_mean_send': '이메일 월 평균 발신 수',
                      'email_month_var_receive': '이메일 월 분산 수신 수 ',
                      'email_month_var_send': '이메일 월 분산 발신 수 ',
                      'email_reply_delta_mean': '회신 평균 시간 (초)',
                      'email_reply_delta_var': '회신 분산 시간 (초)',
                      'ep_nbr_avg': '하루평균 EP접속 횟수',
                      'ep_nbr_var': '하루 EP접속 횟수 분산',
                      'eval_date_x': '역량 평가 날짜',
                      'exc_i_mean': '팀 소속감 평균 점수',
                      'exc_l_mean': '리더교류 평균 점수',
                      'exc_t_mean': '팀원교류 평균 점수',
                      'exc_v_mean': '본인 의견 개진 평균 점수',
                      'flow_avg': '몰입직접적 2개 질문 평균',
                      'flow_cluster': '몰입도수준 군집화',
                      'food_meanm_dw': '평균월_식대대우인터_이용금액',
                      'food_meanm_gy': '평균월_식대광양_이용금액',
                      'food_meanm_pc': '평균월_식대포스코센터_이용금액',
                      'food_meanm_pg': '평균월_식대포스코건설_이용금액',
                      'food_meanm_ph': '평균월_식대포항_이용금액',
                      'food_meanm_pr': '평균월_식대포스코R_이용금액',
                      'food_tot_meanm': '월 평균 식대 총 지출',
                      'food_tot_spend': '총_식당_이용금액',
                      'food_totm_dw': '총_식대대우인터_이용월횟수',
                      'food_totm_gy': '총_식대광양_이용월횟수',
                      'food_totm_pc': '총_식대포스코센터_이용월횟수',
                      'food_totm_pg': '총_식대포스코건설_이용월횟수',
                      'food_totm_ph': '총_식대포항_이용월횟수',
                      'food_totm_pr': '총_식대포스코R_이용월횟수',
                      'grade_co_r1_avg': '최근 1년 동안 역량 동료등급 평균',
                      'grade_co_r3_avg': '최근 3년 동안 역량 동료등급 평균',
                      'grade_co_y': '역량 동료평가 등급',
                      'grade_emp_r1_avg': '최근 2년 동안 역량 상향등급 평균',
                      'grade_emp_r2_avg': '최근 2년 동안 역량 상향등급 평균',
                      'grade_r1_avg': '최근 1년 동안 성과등급 평균',
                      'grade_r3_avg': '최근 2년 동안 성과등급 평균',
                      'grade_sv1_avg': '최근 1년 동안 역량 하향등급 평균',
                      'grade_sv2_avg': '최근 2년 동안 역량 하향등급 평균',
                      'grade_sv_y': '역량 하향평과 등급',
                      'grade_y': '성과 등급',
                      'id': '사번',
                      'ims_tot_board_enroll': '총_임원창의_횟수',
                      'ims_tot_board_opinion_enroll': '총_임원창의의견_횟수',
                      'ims_tot_enroll': 'IMS_총_등록횟수',
                      'ims_tot_idea_enroll': '총_아이디어_등록횟수',
                      'ims_tot_opinion_enroll': '총_의견등록_횟수',
                      'lang_nbr': '어학점수개수',
                      'meet_atd_tot': '회의 참석 총 횟수',
                      'meet_len_avg': '평균 회의 길이',
                      'mep_early_day': '오전 일찍 모바일 EP 접속한 날짜 수',
                      'mep_early_tot': '오전 일찍 모바일 EP 접속 총 횟수',
                      'mep_late_day': '밤 늦게 모바일 EP 접속한 날짜 수 ',
                      'mep_late_tot': '밤 늦게 모바일 EP 접속 총 횟수',
                      'pccontrol_mean_timeh': '평균_PC제어_결재요시간',
                      'pccontrol_tot_request': '총_PC제어_요청횟수',
                      'pccontrol_tot_sign': '총_PC제어_결재횟수',
                      'pcdrm_tot_decoding': '총_PCDRM_복호화건수',
                      'pcdrm_tot_print': '총_PCDRM_인쇄건수',
                      'pcm_tot_check': '총_PCM조회수',
                      'pcm_tot_checked': '총_PCM피조회수',
                      'pcm_tot_enroll': '총_PCM등록수',
                      'pcm_tot_remove': '총_PCM삭제수',
                      'pcout_mean_timeh': '평균_PC반출_결재소요시간',
                      'pcout_tot_request': '총_PC반출_요청횟수',
                      'pcout_tot_sign': '총_PC반출_결재횟수',
                      'place': '근무지',
                      'porta_mean_tiemh': '평균_휴대용장치_결재소요시간',
                      'porta_tot_request': '총_휴대용장치_요청횟수',
                      'porta_tot_sign': '총_휴대용장치_결재횟수',
                      'print_tot': '문서 인쇄 횟수 ',
                      'rewardyn': '포상유무',
                      'same_dep_high_betweenness': '같은부서 높은레벨_매개중심성',
                      'same_dep_high_closeness': '같은부서 높은레벨_근접중심성',
                      'same_dep_high_eigenvector': '같은부서 높은레벨_고유벡터중심성',
                      'same_dep_high_indegree': '같은부서 높은레벨_연결내향중심성',
                      'same_dep_high_outdegree': '같은부서 높은레벨_연결외향중심성',
                      'same_dep_low_betweenness': '같은부서 낮은레벨_매개중심성',
                      'same_dep_low_closeness': '같은부서 낮은레벨_근접중심성',
                      'same_dep_low_eigenvector': '같은부서 낮은레벨_고유벡터중심성',
                      'same_dep_low_indegree': '같은부서 낮은레벨_연결내향중심성',
                      'same_dep_low_outdegree': '같은부서 낮은레벨_연결외향중심성',
                      'sangsa_betweenness': '상사_매개중심성',
                      'sangsa_closeness': '상사_근접중심성',
                      'sangsa_eigenvector': '상사_고유벡터중심성',
                      'sangsa_indegree': '상사_연결내향중심성',
                      'sangsa_outdegree': '상사_연결외향중심성',
                      'severdrm_tot_print': '총_서버DRM_인쇄건수',
                      'sex': '성별',
                      'sna_betweenness': '매개중심성',
                      'sna_closeness': '근접중심성',
                      'sna_eigenvector': '고유벡터중심성',
                      'sna_indegree': '연결내향중심성',
                      'sna_outdegree': '연결외향중심성',
                      'thank_letter_tot_receive': '감사편지수신횟수',
                      'thank_letter_tot_send': '감사편지발신횟수',
                      'thank_mms_tot_receive': '감사문자수신횟수',
                      'thank_mms_tot_send': '감사문자발신횟수',
                      'thank_note_tot_comment': '감사노트댓글횟수',
                      'thank_note_tot_receive': '감사노트수신횟수',
                      'thank_note_tot_send': '감사노트발신횟수',
                      'thank_note_tot_sympathy': '감사노트공감횟수',
                      'thank_receive': '각종 감사 총 받은 횟수',
                      'thank_send': '각종 감사 총 보낸 횟수',
                      'thank_token_tot_receive': '감사토큰수신횟수',
                      'thank_token_tot_send': '감사토큰발신횟수',
                      'tipi_a': '공감적인 성격 점수',
                      'tipi_a_mean': 'A성격점수 - 성격평균점수',
                      'tipi_c': '부지러한 성격 점수',
                      'tipi_c_mean': 'C성격점수 - 성격평균점수',
                      'tipi_e': '외향적인 성격 점수',
                      'tipi_e_mean': 'E성격점수 - 성격평균점수',
                      'tipi_es': '정석적으로 안정적인 성격 점수',
                      'tipi_es_mean': 'ES성격점수 - 성격평균점수',
                      'tipi_oe': '사고가 열려있는 성격 점수',
                      'tipi_oe_mean': 'OE성격점수 - 성격평균점수',
                      'tms_tot_attendant': '총_수행자된_횟수',
                      'tms_tot_coworker': '총_협업자된_횟수',
                      'vdi_indi_mean_timem': 'VDI_개별_사용minute',
                      'vdi_indi_tot_access': 'VDI_개별_총접속횟수',
                      'vdi_share_mean_timem': 'VDI_공용_사용minute',
                      'vdi_share_tot_access': 'VDI_공용_총접속횟수',
                      'vdi_tot_access': 'vdi 접속 총 횟수',
                      'vdi_tot_mean_timem': 'vdi 접속 총 시간',
                      'work_duration': '근무기간'}
        return var_hanvar

    def get_varname_explain(self):
        var_explain = {'age': '현재 나이 (데이터 추출 당시)',
                         'approve_mean_timeh': '1년 동안 결재요청건수 당 평균 승인소요 시간 (평균 결재 소요 시간, 단위 : 시)',
                         'approve_tot_request': '1년 동안 결재 요청 총 횟수',
                         'apprvoe_tot_sign': '1년 동안 결재 요청을 승인한 총 횟수',
                         'blog_tot_checked': '1년 동안 블로그 게시글 피조회 총 횟수',
                         'blog_tot_visit': '1년 동안 타블로그 접속 총 횟수',
                         'blog_tot_visited': '1년 동안 my블로그 방문자 총 명 수',
                         'btrip_nbr': '1년 동안 총 출장 일수',
                         'bu': '부.그룹. 이 아닌 그냥 부 (최소단위)',
                         'buha_betweenness': '부하 대상 두 직원간의 최단경로에 해당직원이 속해있을 확률 (사용 불가) 기준의 SNA 값',
                         'buha_closeness': '부하 대상 직원이 메일을 직접적으로 주고받은 직원 수 기준의 SNA 값',
                         'buha_eigenvector': '부하 대상 직원이 중심성이 높은 다른 직원과 메일을 주고받은 정도 기준의 SNA 값',
                         'buha_indegree': '부하 대상 직원이 받은 메일 수 기준 (일 평균)',
                         'buha_outdegree': '부하 대상 직원이 보낸 메일 수 기준 (일 평균)',
                         'cafe_meanm_pg1f': '1년 동안 카페판교1층 평균 월 이용 금액',
                         'cafe_meanm_pg3f': '1년 동안 카페판교3층 평균 월 이용 금액',
                         'cafe_tot_spend': '1년 동안 카페 총 이용 금액',
                         'cafe_totm_pg1f': '1년 동안 카페판교1층 총 이용 개월 수 ',
                         'cafe_totm_pg3f': '1년 동안 카페판교3층 총 이용 개월 수 ',
                         'cct1': '13. 나는 지난 2주동안, 일할 때는 일 외의 다른 것들에 대해 아무 생각이 들지 않았다',
                         'cct2': '14. 업무를 할 때, 나는 에너지가 넘치는 걸 느낀다.',
                         'cct3': '15. 나에게 있어 포스코ICT는 내가 일할 수 있는 회사들 중에서 최고라고 생각한다. ',
                         'cct4': '16. 나는 지난 2주동안 내 일에 완전히 몰두하였다.',
                         'cct5': '17. 적은 보수를 받더라도 나는 여전히 이 일을 하고 싶다',
                         'cct_avg': '업무몰입도 5개질문 점수의 평균',
                         'cct_no_reply_nbr': '업무몰입도 5개질문 중 무응답 개수 질문',
                         'coreyn': '핵심인재 인지 아닌 지',
                         'decode_tot': '(복호화 횟수+복호화 신청 횟수)',
                         'diff_dep_high_betweenness': '다른부서 높은레벨 대상 두 직원간의 최단경로에 해당직원이 속해있을 확률 (사용 불가) 기준의 SNA 값',
                         'diff_dep_high_closeness': '다른부서 높은레벨 대상 직원이 메일을 직접적으로 주고받은 직원 수 기준의 SNA 값',
                         'diff_dep_high_eigenvector': '다른부서 높은레벨 대상 직원이 중심성이 높은 다른 직원과 메일을 주고받은 정도 기준의 SNA 값',
                         'diff_dep_high_indegree': '다른부서 높은레벨 대상 직원이 받은 메일 수 기준 (일 평균)',
                         'diff_dep_high_outdegree': '다른부서 높은레벨 대상 직원이 보낸 메일 수 기준 (일 평균)',
                         'diff_dep_low_betweenness': '다른부서 낮은레벨 대상 두 직원간의 최단경로에 해당직원이 속해있을 확률 (사용 불가) 기준의 SNA 값',
                         'diff_dep_low_closeness': '다른부서 낮은레벨 대상 직원이 메일을 직접적으로 주고받은 직원 수 기준의 SNA 값',
                         'diff_dep_low_eigenvector': '다른부서 낮은레벨 대상 직원이 중심성이 높은 다른 직원과 메일을 주고받은 정도 기준의 SNA 값',
                         'diff_dep_low_indegree': '다른부서 낮은레벨 대상 직원이 받은 메일 수 기준 (일 평균)',
                         'diff_dep_low_outdegree': '다른부서 낮은레벨 대상 직원이 보낸 메일 수 기준 (일 평균)',
                         'docu_decoding_mean_timeh': '1년 동안 문서복호화 결재요청 건수 당 평균 승인소요 시간 (평균 결재 소요 시간, 단위:시)',
                         'docu_decoding_tot_n': '1년 동안 문서복호화 신청 문서 총 건수',
                         'docu_decoding_tot_requet': '1년 동안 문서복호화 요청 총 횟수',
                         'docu_decoding_tot_sign': '1년 동안 문서복호화 결재 총 횟수',
                         'dongryo_betweenness': '동료 대상 두 직원간의 최단경로에 해당직원이 속해있을 확률 (사용 불가) 기준의 SNA 값',
                         'dongryo_closeness': '동료 대상 직원이 메일을 직접적으로 주고받은 직원 수 기준의 SNA 값',
                         'dongryo_eigenvector': '동료 대상 직원이 중심성이 높은 다른 직원과 메일을 주고받은 정도 기준의 SNA 값',
                         'dongryo_indegree': '동료 대상 직원이 받은 메일 수 기준 (일 평균)',
                         'dongryo_outdegree': '동료 대상 직원이 보낸 메일 수 기준 (일 평균)',
                         'eat_tot_spend': '1년 동안 식당카페 총 이용 금액',
                         'ecm_after_lunch1314': '3개월 동안 1pm~2pm(점심 후) ECM을 이용한 일 수',
                         'ecm_after_out1904': '3개월 동안 7pm~4am(야근 시간) ECM을 이용한 일 수',
                         'ecm_before_in79': '3개월 동안 7am~9am(출근 전) ECM을 이용한 일 수',
                         'ecm_before_out1718': '3개월 동안 5pm~6pm(퇴근 전) ECM을 이용한 일 수',
                         'ecm_tot_enroll': '1년 동안 ECM 등록 총 횟수',
                         'edu_abroad': '1년 동안 총 해외연수이수학점',
                         'edu_course_cnt': '1년 동안 총 직무이수학점+비직무이수학점 (=사내이수학점+사외이수학점)',
                         'edu_job': '1년 동안 총 직무이수학점',
                         'edu_license': '1년 동안 총 자격취득이수학점',
                         'edu_nbr': '1년 동안 총 교육이수과정 수 ',
                         'edu_njob': '1년 동안 총 비직무이수학점',
                         'edu_out_ratio': '1년 동안 사외이수학점/교육이수학점',
                         'email_after_lunch1314_mean': '1년 동안 1pm~2pm(점심 후) 메일 발신 횟수 평균',
                         'email_between_1904_daycnt_send': '1년 동안 7pm~4am(야근 시간) 메일 발신 일 수',
                         'email_between_1904_mean_send': '1년 동안 7pm~4am(야근 시간) 메일 발신 횟수 평균',
                         'email_before_out1718_mean': '1년 동안 5pm~6pm(퇴근 전) 메일 발신 횟수 평균',
                         'email_between_0709_daycnt_send': '1년 동안 7am~9am(출근 전) 메일 발신 일 수',
                         'email_before_time79_mean': '1년 동안 7am~9am(출근 전) 메일 발신 횟수 평균',
                         'email_day_mean_receive': '개인이 하루에 받는 메일수신 개수의 분산 (1년간 데이터 분산)',
                         'email_day_mean_send': '개인이 하루에 보내는 메일송신 개수의 평균 (1년간 데이터 평균)',
                         'email_day_var_receive': '개인이 하루에 받는 메일수신 개수의 평균 (1년간 데이터 평균)',
                         'email_day_var_send': '개인이 하루에 보내는 메일송신 개수의 분산 (1년간 데이터 분산)',
                         'email_month_mean_receive': '개인이 한달에 받는 메일수신 개수의 평균 (1년간 데이터 평균)',
                         'email_month_mean_send': '개인이 한달에 보내는 메일송신 개수의 평균 (1년간 데이터 평균)',
                         'email_month_var_receive': '개인이 한달에 받는 메일수신 개수의 분산 (1년간 데이터 분산)',
                         'email_month_var_send': '개인이 한달에 보내는 메일송신 개수의 분산 (1년간 데이터 분산)',
                         'email_reply_delta_mean': '개인이 어떤 메일에 대해, 회신시간 - 수신시간(시 단위)를 전체 데이터에서 평균 ',
                         'email_reply_delta_var': '개인이 어떤 메일에 대해, 회신시간 - 수신시간(시 단위)를 전체 데이터에서 분산',
                         'ep_nbr_avg': '1년 동안 하루 평균 EP접속 횟수',
                         'ep_nbr_var': '1년 동안 하루분산 EP접속 횟수',
                         'eval_date_x': '평가일',
                         'exc_i_mean': '팀 소속감',
                         'exc_l_mean': 'Leader-Member Exchange 리더교류',
                         'exc_t_mean': 'Team-Member Exchange 팀원교류',
                         'exc_v_mean': 'voice behavior 본인 의견 개진',
                         'flow_avg': '몰입 직접적으로 물어본 13,16번 질문 2개의 평균',
                         'flow_cluster': '몰입도 수준 군집화 ',
                         'food_meanm_dw': '1년 동안 식대대우인터 평균 월 이용 금액',
                         'food_meanm_gy': '1년 동안 식대광양 평균 월 이용 금액',
                         'food_meanm_pc': '1년 동안 식대포스코센터 평균 월 이용 금액',
                         'food_meanm_pg': '1년 동안 식대포스코건설 평균 월 이용 금액',
                         'food_meanm_ph': '1년 동안 식대포항 평균 월 이용 금액',
                         'food_meanm_pr': '1년 동안 식대포스코R 평균 월 이용 금액',
                         'food_tot_meanm': '지역 별 월 평균 식대 총 합(카페 제외)',
                         'food_tot_spend': '1년 동안 식당 총 이용 금액',
                         'food_totm_dw': '1년 동안 식대대우인터 총 이용 개월 수 ',
                         'food_totm_gy': '1년 동안 식대광양 총 이용 개월 수 (Max : 12)',
                         'food_totm_pc': '1년 동안 식대포스코센터 총 이용 개월 수 ',
                         'food_totm_pg': '1년 동안 식대포스코건설 총 이용 개월 수 ',
                         'food_totm_ph': '1년 동안 식대포항 총 이용 개월 수 ',
                         'food_totm_pr': '1년 동안 식대포스코R 총 이용 개월 수 ',
                         'grade_co_r1_avg': '최근 2번의 평가 역량 동료등급의 평균',
                         'grade_co_r3_avg': '최근 3년 역량 동료등급의 평균',
                         'grade_co_y': '역량 동료평가 등급 (동료로부터 평가)',
                         'grade_emp_r1_avg': '최근 2번의 평가 역량 상향등급의 평균',
                         'grade_emp_r2_avg': '최근 4번의 평가 역량 상향등급의 평균',
                         'grade_r1_avg': '최근 2번의 평가 성과 등급의 평균',
                         'grade_r3_avg': '최근 3년 성과 등급의 평균',
                         'grade_sv1_avg': '최근 2번의 평가 역량 하양등급의 평균',
                         'grade_sv2_avg': '최근 4번의 평가 역량 하양등급의 평균',
                         'grade_sv_y': '역량 하향평과 등급 (상사가 직원 평가)',
                         'grade_y': '성과 등급',
                         'id': '휴직 제외 정규직, P1~P6,  광양, 분당, 서울, 서울(성북), 서울(강남), 포스코센타, 포항 (1828명)',
                         'ims_tot_board_enroll': '1년 동안 임원창의 구분으로 IMS에 올린 글 총 개수',
                         'ims_tot_board_opinion_enroll': '1년 동안 임원창의의견 구분으로 IMS에 올린 글 총 개수',
                         'ims_tot_enroll': '1년 동안 (아이디어, 의견등록, 임원창의, 임원창의의견) 구분없이 IMS에 올린 글 총 개수',
                         'ims_tot_idea_enroll': '1년 동안 아이디어 구분으로 IMS에 올린 글 총 개수',
                         'ims_tot_opinion_enroll': '1년 동안 의견등록 구분으로 IMS에 올린 글 총 개수',
                         'lang_nbr': '1년 동안 토익스피킹, 오픽, TSC, SJPT 중 몇개 어학 점수 가지고 있는가',
                         'meet_atd_tot': '1년 동안 회의 참석 총 횟수',
                         'meet_len_avg': '회의 한번 참석 했을때 걸리는 평균 시간',
                         'mep_early_day': '오전 7~9시 모바일EP 접속한 날짜 수',
                         'mep_early_tot': '오전 7~9시 모바일EP 접속 총 횟수',
                         'mep_late_day': '밤 19~04시 모바일EP 접속한 날짜 수',
                         'mep_late_tot': '밤 19~04시 모바일EP 접속 총 횟수',
                         'pccontrol_mean_timeh': '1년 동안 PC제어 결재요청 건수 당 평균 승인소요 시간 (평균 결재 소요 시간, 단위:시)',
                         'pccontrol_tot_request': '1년 동안 PC제어 요청 총 횟수',
                         'pccontrol_tot_sign': '1년 동안 PC제어 결재 총 횟수',
                         'pcdrm_tot_decoding': '1년 동안 PCDRM 복호화 총 횟수',
                         'pcdrm_tot_print': '1년 동안 PCDRM 인쇄 총 횟수',
                         'pcm_tot_check': '1년 동안 PCM 총 조회 수',
                         'pcm_tot_checked': '1년 동안 PCM 총 피조회 수',
                         'pcm_tot_enroll': '1년 동안 PCM 총 등록 수 ',
                         'pcm_tot_remove': '1년 동안 PCM 총 삭제 수',
                         'pcout_mean_timeh': '1년 동안 PC반출 결재요청 건수 당 평균 승인소요 시간 (평균 결재 소요 시간, 단위:시)',
                         'pcout_tot_request': '1년 동안 PC반출 요청 총 횟수',
                         'pcout_tot_sign': '1년 동안 PC반출 결재 총 횟수',
                         'place': '실제 등록된 근무지와 근무지별 월별 평균 식대이용금액 이용한 추정 확정 근무지 결과',
                         'porta_mean_tiemh': '1년 동안 휴대용장치 반출 결재요청 건수 당 평균 승인소요 시간 (평균 결재 소요 시간, 단위:시)',
                         'porta_tot_request': '1년 동안 휴대용장치 반출 요청 총 횟수',
                         'porta_tot_sign': '1년 동안 휴대용장치 반출 결재 총 횟수',
                         'print_tot': '서버인쇄 + DRM인쇄',
                         'rewardyn': '1년 동안 포상 유무',
                         'same_dep_high_betweenness': '같은부서 높은레벨 대상 두 직원간의 최단경로에 해당직원이 속해있을 확률 (사용 불가) 기준의 SNA 값',
                         'same_dep_high_closeness': '같은부서 높은레벨 대상 직원이 메일을 직접적으로 주고받은 직원 수 기준의 SNA 값',
                         'same_dep_high_eigenvector': '같은부서 높은레벨 대상 직원이 중심성이 높은 다른 직원과 메일을 주고받은 정도 기준의 SNA 값',
                         'same_dep_high_indegree': '같은부서 높은레벨 대상 직원이 받은 메일 수 기준 (일 평균)',
                         'same_dep_high_outdegree': '같은부서 높은레벨 대상 직원이 보낸 메일 수 기준 (일 평균)',
                         'same_dep_low_betweenness': '같은부서 낮은레벨 대상 두 직원간의 최단경로에 해당직원이 속해있을 확률 (사용 불가) 기준의 SNA 값',
                         'same_dep_low_closeness': '같은부서 낮은레벨 대상 직원이 메일을 직접적으로 주고받은 직원 수 기준의 SNA 값',
                         'same_dep_low_eigenvector': '같은부서 낮은레벨 대상 직원이 중심성이 높은 다른 직원과 메일을 주고받은 정도 기준의 SNA 값',
                         'same_dep_low_indegree': '같은부서 낮은레벨 대상 직원이 받은 메일 수 기준 (일 평균)',
                         'same_dep_low_outdegree': '같은부서 낮은레벨 대상 직원이 보낸 메일 수 기준 (일 평균)',
                         'sangsa_betweenness': '상사 대상 두 직원간의 최단경로에 해당직원이 속해있을 확률 (사용 불가) 기준의 SNA 값',
                         'sangsa_closeness': '상사 대상 직원이 메일을 직접적으로 주고받은 직원 수 기준의 SNA 값',
                         'sangsa_eigenvector': '상사 대상 직원이 중심성이 높은 다른 직원과 메일을 주고받은 정도 기준의 SNA 값',
                         'sangsa_indegree': '상사 대상 직원이 받은 메일 수 기준 (일 평균)',
                         'sangsa_outdegree': '상사 대상 직원이 보낸 메일 수 기준 (일 평균)',
                         'severdrm_tot_print': '1년 동안 서버DRM 인쇄 총 횟수',
                         'sex': 'Female / Male',
                         'sna_betweenness': '두 직원간의 최단경로에 해당직원이 속해있을 확률 (사용 불가) 기준의 SNA 값',
                         'sna_closeness': '직원이 메일을 직접적으로 주고받은 직원 수 기준의 SNA 값',
                         'sna_eigenvector': '직원이 중심성이 높은 다른 직원과 메일을 주고받은 정도 기준의 SNA 값',
                         'sna_indegree': '직원이 받은 메일 수 기준 (일 평균)',
                         'sna_outdegree': '직원이 보낸 메일 수 기준 (일 평균)',
                         'thank_letter_tot_receive': '1년 도앙 감사편지 수신 총 횟수',
                         'thank_letter_tot_send': '1년 동안 감사판지 발신 총 횟수',
                         'thank_mms_tot_receive': '1년 동안 감사문자 수신 총 횟수',
                         'thank_mms_tot_send': '1년 동안 감사문자 발신 총 횟수',
                         'thank_note_tot_comment': '1년 동안 감사노트에 등록한 댓글의 총 개수',
                         'thank_note_tot_receive': '1년 동안 감사노트 수신 총 횟수',
                         'thank_note_tot_send': '1년 동안 감사노트 발신 총 횟수',
                         'thank_note_tot_sympathy': '1년 동안 감사노트에 공감한 총 횟수',
                         'thank_receive': '감사 종류 4개 수신 총 합',
                         'thank_send': '감사 종류 4개 발신 총 합',
                         'thank_token_tot_receive': '1년 동안 감사토큰 수신 총 횟수',
                         'thank_token_tot_send': '1년 동안 감사토큰 발신 총 횟수',
                         'tipi_a': 'A: Agreeableness',
                         'tipi_a_mean': 'A: Agreeableness - 5가지 성격 점수 평균',
                         'tipi_c': 'C: Conscientiousness',
                         'tipi_c_mean': 'C: Conscientiousness - 5가지 성격 점수 평균',
                         'tipi_e': 'E: Extraversion',
                         'tipi_e_mean': 'E: Extraversion - 5가지 성격 점수 평균',
                         'tipi_es': 'ES: Emotional stability (반대=화를 잘내고 걱정이 많은 사람)',
                         'tipi_es_mean': 'ES: Emotional stability (반대=화를 잘내고 걱정이 많은 사람) - 5가지 성격 점수 평균',
                         'tipi_oe': 'OE: Openness to Experiences',
                         'tipi_oe_mean': 'OE: Openness to Experiences - 5가지 성격 점수 평균',
                         'tms_tot_attendant': '1년 동안 TMS 수행자로 등록된 횟수',
                         'tms_tot_coworker': '1년 동안 TMS 협업자로 등록된 총 횟수',
                         'vdi_indi_mean_timem': '1년 동안 개별 VDI 평균 사용시간 (한번 접속 시, 단위 : 분)',
                         'vdi_indi_tot_access': '1년 동안 개별 VDI 총 접속 횟수',
                         'vdi_share_mean_timem': '1년 동안 공용 VDI 평균 사용시간 (한번 접속 시, 단위 : 분)',
                         'vdi_share_tot_access': '1년 동안 공용 VDI 총 접속 횟수',
                         'vdi_tot_access': 'vdi 개별 + vdi 공용 접속횟수',
                         'vdi_tot_mean_timem': 'vdi 개별 + vdi 공용 접속시간',
                         'work_duration': '총 근무 기간 (데이터 추출 당시)'}

        return var_explain
