# Generated by Django 2.0.7 on 2018-08-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('edu_course_cnt', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('sendCnt', models.FloatField(default=0, null=True)),
                ('sendCnt_nwh', models.FloatField(default=0, null=True)),
                ('receiveCnt', models.FloatField(default=0, null=True)),
                ('sendCnt_byLevelRatio', models.FloatField(default=0, null=True)),
                ('sendCnt_nwh_byLevelRatio', models.FloatField(default=0, null=True)),
                ('receiveCnt_byLevelRatio', models.FloatField(default=0, null=True)),
                ('nodeSize', models.FloatField(default=0, null=True)),
                ('nodeSize_byLevelRatio', models.FloatField(default=0, null=True)),
                ('nodeSize_byGroupRatio', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDateBeginEnd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eval_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nwh', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eval_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bu', models.CharField(max_length=50, null=True)),
                ('level', models.IntegerField(null=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('empname', models.CharField(max_length=30, null=True)),
                ('place', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBiography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('bu', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('level', models.IntegerField(null=True)),
                ('empname', models.CharField(max_length=30, null=True)),
                ('place', models.CharField(max_length=30, null=True)),
                ('holiday', models.FloatField(null=True)),
                ('start_date', models.DateTimeField()),
                ('eval_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('grade_sv_y_3', models.FloatField(null=True)),
                ('grade_sv_y_2', models.FloatField(null=True)),
                ('grade_sv_y_1', models.FloatField(null=True)),
                ('grade_sv_r3_avg', models.FloatField(null=True)),
                ('grade_co_y_1', models.FloatField(null=True)),
                ('grade_co_y_2', models.FloatField(null=True)),
                ('grade_co_y_3', models.FloatField(null=True)),
                ('grade_co_r3_avg', models.FloatField(null=True)),
                ('grade_6', models.FloatField(null=True)),
                ('grade_5', models.FloatField(null=True)),
                ('grade_4', models.FloatField(null=True)),
                ('grade_3', models.FloatField(null=True)),
                ('grade_2', models.FloatField(null=True)),
                ('grade_1', models.FloatField(null=True)),
                ('grade_r3_avg', models.FloatField(null=True)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='GatePass_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_date', models.DateTimeField()),
                ('isIn', models.BooleanField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='GatePassData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('staying_office_meanM', models.FloatField(null=True)),
                ('staying_office_meanStr', models.CharField(max_length=20, null=True)),
                ('outting_freq_mean', models.FloatField(null=True)),
                ('inTime_mean', models.FloatField(null=True)),
                ('outTime_mean', models.FloatField(null=True)),
                ('inTime_meanStr', models.CharField(max_length=20, null=True)),
                ('outTime_meanStr', models.CharField(max_length=20, null=True)),
                ('working_days', models.FloatField(default=0, null=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('leadership_env_job', models.FloatField(null=True)),
                ('leadership_env', models.FloatField(null=True)),
                ('leadership_env_common', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LogFirstLast',
            fields=[
                ('modelName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='M_EP_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='M_EPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('mep_normal', models.FloatField(default=0, null=True)),
                ('mep_early', models.FloatField(default=0, null=True)),
                ('mep_late', models.FloatField(default=0, null=True)),
                ('mep_normal_byLevelRatio', models.FloatField(default=0, null=True)),
                ('mep_early_byLevelRatio', models.FloatField(default=0, null=True)),
                ('mep_late_byLevelRatio', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Token_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('token_send', models.FloatField(default=0, null=True)),
                ('token_receive', models.FloatField(default=0, null=True)),
                ('token_send_byLevelRatio', models.FloatField(default=0, null=True)),
                ('token_receive_byLevelRatio', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Token_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiveID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_receiveID', to='index.Employee')),
                ('sendID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_sendID', to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='VDI_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('vdi_normal', models.FloatField(default=0, null=True)),
                ('vdi_early', models.FloatField(default=0, null=True)),
                ('vdi_late', models.FloatField(default=0, null=True)),
                ('vdi_normal_byLevelRatio', models.FloatField(default=0, null=True)),
                ('vdi_early_byLevelRatio', models.FloatField(default=0, null=True)),
                ('vdi_late_byLevelRatio', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='VDI_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='emaillog',
            name='receiveID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_receiveID', to='index.Employee'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sendID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_sendID', to='index.Employee'),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='employeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee'),
        ),
        migrations.AddField(
            model_name='education',
            name='employeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee'),
        ),
    ]
