# Generated by Django 2.0.7 on 2018-07-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdi_log',
            name='eval_date',
            field=models.DateTimeField(),
        ),
    ]
