# Generated by Django 2.0.5 on 2018-08-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('isTarget', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Employee')),
            ],
        ),
    ]
