# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180220_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval_log',
            name='approve_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 15, 33, 27, 383081)),
        ),
    ]
