# Generated by Django 2.0.5 on 2018-08-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180731_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFirstLast',
            fields=[
                ('modelName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
