# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180220_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMS_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_date', models.DateTimeField()),
                ('employeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='index.Employee')),
                ('employeeID2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooperator', to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TMSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('tms_tot_attendant', models.FloatField(default=0, null=True)),
                ('tms_tot_coworker', models.FloatField(default=0, null=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='approval_log',
            name='approve_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 16, 10, 37, 794589)),
        ),
    ]
