# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180220_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_date', models.DateTimeField()),
                ('isIn', models.BooleanField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='GatePassData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID_confirm', models.IntegerField(default=0)),
                ('eval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('staying_office_meanh', models.FloatField(default=0, null=True)),
                ('outting_meanh', models.FloatField(default=0, null=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='approval_log',
            name='approve_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 16, 58, 42, 648489)),
        ),
    ]
