# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180222_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepassdata',
            name='outting_meanh',
        ),
        migrations.RemoveField(
            model_name='gatepassdata',
            name='staying_office_meanh',
        ),
        migrations.AddField(
            model_name='gatepassdata',
            name='outting_freq_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gatepassdata',
            name='staying_office_meanM',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='approval_log',
            name='approve_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 14, 19, 24, 184177)),
        ),
    ]
