# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20180222_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval_log',
            name='approve_date',
            field=models.DateTimeField(),
        ),
    ]
