# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20180222_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassdata',
            name='working_days',
            field=models.FloatField(default=0, null=True),
        ),
    ]
