# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_gatepassdata_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassdata',
            name='inTime_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gatepassdata',
            name='inTime_meanStr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gatepassdata',
            name='outTime_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gatepassdata',
            name='outTime_meanStr',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
