# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20180223_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassdata',
            name='staying_office_meanStr',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
