# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_gatepassdata_staying_office_meanstr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaildata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emaildata',
            name='email_before_time79_daycnt',
        ),
        migrations.RemoveField(
            model_name='emaildata',
            name='email_between_1904_daycnt_send',
        ),
        migrations.RemoveField(
            model_name='emaildata',
            name='email_between_1904_mean_send',
        ),
    ]
