# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20180227_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildata',
            name='all_degree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='buha_betweenness',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='buha_degree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='buha_eigenvector',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='buha_indegree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='buha_outdegree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='dongryo_betweenness',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='dongryo_degree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='dongryo_eigenvector',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='dongryo_indegree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='dongryo_outdegree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_0709_daycnt_receive',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_0709_daycnt_send',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_0709_mean_receive',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_0709_mean_send',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_1314_mean_receive',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_1314_mean_send',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_1718_mean_receive',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_1718_mean_send',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_1904_daycnt_receive',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_1904_daycnt_send',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_1904_mean_receive',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_between_1904_mean_send',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_day_var_receive',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_day_var_send',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_month_mean_receive',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_month_mean_send',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email_month_var_send',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='sangsa_betweenness',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='sangsa_closeness',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='sangsa_degree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='sangsa_indegree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='sangsa_outdegree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='sna_betweenness',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='sna_eigenvector',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='sna_indegree',
            field=models.FloatField(default=0, null=True),
        ),
    ]
