# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20180227_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaildata',
            name='all_degree',
        ),
        migrations.RemoveField(
            model_name='emaildata',
            name='buha_degree',
        ),
        migrations.RemoveField(
            model_name='emaildata',
            name='dongryo_degree',
        ),
        migrations.RemoveField(
            model_name='emaildata',
            name='sangsa_degree',
        ),
    ]
