# Generated by Django 2.0.5 on 2018-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20180727_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeegrade',
            name='grade_co_y',
        ),
        migrations.AddField(
            model_name='employeegrade',
            name='grade_co_r2_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='employeegrade',
            name='grade_co_y_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='employeegrade',
            name='grade_co_y_2',
            field=models.FloatField(null=True),
        ),
    ]
